#!/bin/sh

SCRIPTNAME=$0
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/init.d/init_utilities

start_function() {
	# install cifs module 
	if [ -f /lib/modules/2.6.28/cifs.ko ]
	then
		debug_print "Installing cifs module.."
		insmod cifs.ko
	else
		debug_print "No cifs module..."
	fi
}

stop_function() {
	debug_print "Doing nothing"
}

case $1 in
    "start")
        start_function
        ;;
    "stop")
        stop_function
        ;;
    "restart")
        stop_function
        start_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
