#!/bin/sh

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0

. /etc/init.d/init_utilities

start_function() {
	try_command insmod /lib/modules/2.6.28/lzo_compress.ko
	try_command insmod /lib/modules/2.6.28/lzo_decompress.ko
	try_command insmod /lib/modules/2.6.28/ramzswap.ko num_devices=1
#	try_command mknod /dev/ramzswap0 b 253 0
	/opt/local/sbin/rzscontrol /dev/ramzswap0 --init 2>&1 >/dev/null
	# sometimes it takes /dev/ramzswap0 a bit more to instanciate
	count=5
	while [ ! -b /dev/ramzswap0 -a $count -gt 0 ]
	do
		sleep 1
		count=$(expr $count - 1)
	done
	/sbin/swapon /dev/ramzswap0
	# ignore errors. bad, but better than not starting up
	exit 0
}

stop_function() {
	/sbin/swapoff /dev/ramzswap0
	rmmod ramzswap
	rm -f /dev/ramzswap0 2>&1 >/dev/null
	rmmod lzo_decompress
	rmmod lzo_compress
	exit 0
}

case $1 in
    "start")
    start_function
    ;;
    "stop")
    stop_function
    ;;
    "restart")
    stop_function
    start_function
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
esac
