#!/bin/sh

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/init.d/init_utilities

start_function() {
    # Load HDMI driver
    try_command /bin/load_pd /lib/pd_hdmi.so
}

stop_function() {
    # Remove the HDMI driver
    try_command /bin/unload_pd pd_hdmi
}

case $1 in
    "start")
        start_function
        ;;
    "stop")
        stop_function
        ;;
    "restart")
        stop_function
        start_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
