#!/bin/sh

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/init.d/init_utilities

start_function() {
    try_command insmod /lib/modules/intel_ce_pm.ko
    make_dev intel_ce_pm intel_ce_pm
}

stop_function() {
    rmmod intel_ce_pm
}

case $1 in
    "start")
        start_function
        ;;
    "stop")
        stop_function
        ;;
    "restart")
        stop_function
        start_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
