#!/bin/sh

echo "Entering rc file"

# Setup a 'sane' umask for subprocesses which create files
umask 0022

# Global Constants
DEFAULT_RUNLEVEL=3
# Some sub-scripts need HOSTNAME
export HOSTNAME=intel_ce_linux

# Check for custom run level; if not set choose the default
if [ $# -ge 1 ]; then
    RUNLEVEL=$1;
else
    # Because busybox does not support run levels we won't error.
    #echo "rc ERROR: No run level passed"
    #exit 1
    RUNLEVEL=$DEFAULT_RUNLEVEL
fi

# Source the user profile of enviromental variables and aliases
. /etc/profile

# Make sure our init directory exists
if [ -d /etc/rc$RUNLEVEL.d ]; then
    # Call 'stop' on all processes which start with a K
    # TODO: This section is currently UNTESTED
    #
    #if [ ! -z `ls /etc/rc$RUNLEVEL.d/K*` ]; then
    #    echo "##### Stopping Scripts #####"
    #    for THIS_SCRIPT in /etc/rc$RUNLEVEL.d/K*
    #    do
    #        $THIS_SCRIPT stop
    #        RET_VAL=$?
    #        if [ $RET_VAL -eq 0 ]; then
    #            echo "$THIS_SCRIPT COMPLETE"
    #        else
    #            echo "$THIS_SCRIPT FAILED [returned: $RET_VAL]"
    #            echo "Failed stop scripts will not terminate the init system."
    #            echo "Continuing to the next script."
    #            echo
    #        fi
    #    done
    #    echo "##### Stopping Scripts Complete ######"
    #fi

    # Call 'start' on all processes which start with a S
    echo "##### Starting Scripts #####"
    for THIS_SCRIPT in /etc/rc$RUNLEVEL.d/S*
    do
        $THIS_SCRIPT start
        RET_VAL=$?
        if [ $RET_VAL -eq 0 ]; then
            echo "$THIS_SCRIPT SUCCESS"
        else
echo "************************************************************************"
echo " ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR"
echo ""
echo "   $THIS_SCRIPT FAILED [returned: $RET_VAL]"
echo "   Exiting SysV init. Bringing up the console if possible."
echo ""
echo " ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR"
echo "************************************************************************"
            echo
            exit 1
        fi
    done
    echo "##### Starting Scripts Complete ######"
else
    echo "rc ERROR: Init directory /etc/init.d/rc$RUNLEVEL.d does not exist"
    exit 1
fi

# Print a few lines to provide a clean break:
echo
echo

exit 0
