#!/bin/sh

SCRIPTNAME=$0
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/init.d/init_utilities

start_function() {
	# install sd card detector module 
	debug_print "Installing card detector module.."
	insmod card_detector.ko
}

stop_function() {
	debug_print "Doing nothing"
}

case $1 in
    "start")
        start_function
        ;;
    "stop")
        stop_function
        ;;
    "restart")
        stop_function
        start_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
