#!/bin/sh
#
#  This file is provided under a dual BSD/GPLv2 license.  When using or
#  redistributing this file, you may do so under either license.
#
#  GPL LICENSE SUMMARY
#
#  Copyright(c) 2007-2009 Intel Corporation. All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of version 2 of the GNU General Public License as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
#  The full GNU General Public License is included in this distribution
#  in the file called LICENSE.GPL.
#
#  Contact Information:
#  intel.com
#  Intel Corporation
#  2200 Mission College Blvd.
#  Santa Clara, CA  95052
#  USA
#  (408) 765-8080
#
#
#  BSD LICENSE
#
#  Copyright(c) 2007-2009 Intel Corporation. All rights reserved.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in
#      the documentation and/or other materials provided with the
#      distribution.
#    * Neither the name of Intel Corporation nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#*/

#==========================================================================
#INTEL CONFIDENTIAL
#Copyright 2006-2009 Intel Corporation All Rights Reserved.
#
#The source code contained or described herein and all documents related to the source code ("Material") are owned by Intel Corporation or its suppliers or licensors. Title to the Material remains with Intel Corporation or its suppliers and licensors. The Material contains trade secrets and proprietary and confidential information of Intel or its suppliers and licensors. The Material is protected by worldwide copyright and trade secret laws and treaty provisions. No part of the Material may be used, copied, reproduced, modified, published, uploaded, posted, transmitted, distributed, or disclosed in any way without Intel's prior express written permission.
#
#No license under any patent, copyright, trade secret or other intellectual property right is granted to or conferred upon you by disclosure or delivery of the Materials, either expressly, by implication, inducement, estoppel or otherwise. Any license under such intellectual property rights must be express and approved by Intel in writing.
#
# =========================================================================

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

# Support for multiple SOCs
SOC_CE4100="SOC_NAME_CE4100"
SOC_CE3100="SOC_NAME_CE3100"
SOC_NAME_UNKNOWN="SOC_NAME_UNKNOWN"
SOC_GEN4="SOC_GENERATION_4"
SOC_GEN3="SOC_GENERATION_3"
SOC_GEN_UNKNOWN="SOC_GENERATION_UNKNOWN"

. /etc/init.d/init_utilities

start_function() {
    # Support for multiple SOCs
#    SOC_NAME=`get_soc_info_utility NAME STRING 2>/dev/null`
		SOC_NAME="SOC_NAME_CE4100"
		
    try_command insmod /lib/modules/ioctl_module.ko
    rm -f /dev/smdmsg
    try_command mknod /dev/smdmsg c 238 0
    try_command insmod /lib/modules/ismdcore.ko
    try_command insmod /lib/modules/ismdclock.ko

    debug_print "Loading ISMD"

    try_command insmod /lib/modules/ismdclock_recovery.ko

	if [ "$SOC_NAME" = "$SOC_CE3100" ]; then
		try_command insmod /lib/modules/ismddemux_v2.ko
	elif [ "$SOC_NAME" = "$SOC_CE4100" ]; then
		try_command insmod /lib/modules/ismddemux_v2.ko
	else
		try_command insmod /lib/modules/ismddemux_v3.ko
	fi;

	if [ "$SOC_NAME" = "$SOC_CE3100" ]; then
		try_command insmod /lib/modules/ismdviddec.ko
	else
		try_command insmod /lib/modules/ismdviddec_v2.ko
	fi;
    try_command insmod /lib/modules/ismdvidpproc.ko
    try_command insmod /lib/modules/ismdvidrend.ko
    try_command insmod /lib/modules/ismdaudio.ko
    try_command insmod /lib/modules/ismdbufmon.ko


    # Load TSOut driver on all platforms other then CE4100
    if [ "$SOC_NAME" != "$SOC_CE4100" ]; then try_command insmod /lib/modules/ismdtsout.ko; fi
}

stop_function() {
    # Support for multiple SOCs
#    SOC_NAME=`get_soc_info_utility NAME STRING 2>/dev/null`
		SOC_NAME="SOC_NAME_CE4100"

    # Unload the TSOut driver IFF it is loaded
    lsmod | grep ismdtsout > /dev/null && rmmod ismdtsout

    rmmod ismdbufmon
    rmmod ismdaudio
    rmmod ismdvidrend
    rmmod ismdvidpproc
    if [ "$SOC_NAME" = "$SOC_CE3100" ]; then
       rmmod ismdviddec
    else
       rmmod ismdviddec_v2
    fi;
    if [ "$SOC_NAME" = "$SOC_CE3100" ]; then
		rmmod ismddemux_v2
    elif [ "$SOC_NAME" = "$SOC_CE4100" ]; then
		rmmod ismddemux_v2
	else
		rmmod ismddemux_v3
	fi;
    rmmod ismdclock_recovery
    rmmod ismdclock
    rmmod ismdcore
    rmmod ioctl_module
    rm -f /dev/smdmsg
}

case $1 in
    "start")
    start_function
    ;;
    "stop")
    stop_function
    ;;
    "restart")
    stop_function
    start_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
